### ISSUE TITLE
Task handling loop dies with ssh error

### ISSUE THREAD

**Issue by soichih** [brain-life/amaretti#13]
I've been seeing an occasional task handling loop failure. The last log was

```
0> Wed Dec 06 2017 20:43:32 GMT+0000 (UTC) - info: removing /mnt/share1/prod/5a0760af47c68d002aad3b0f/5a0760af2767f30030bcf4b3 and workdir if empty
0> Wed Dec 06 2017 20:43:33 GMT+0000 (UTC) - info: this task was requested more than 25 days ago..
0> Wed Dec 06 2017 20:43:33 GMT+0000 (UTC) - info: need to remove this task. resource_ids.length:1
0> Wed Dec 06 2017 20:43:33 GMT+0000 (UTC) - info: removing /N/dc2/scratch/brlife/carbonate-workflows/5a075fd92767f30030bcf4ac/5a075fef2767f30030bcf4ad and workdir if empty
0> Wed Dec 06 2017 20:46:14 GMT+0000 (UTC) - info:  
0> Wed Dec 06 2017 20:46:16 GMT+0000 (UTC) - info: couldn't load package.json - using default
0> Wed Dec 06 2017 20:46:16 GMT+0000 (UTC) - info: HEAD is now at 4e63e40 removed unnecessary code

0> Wed Dec 06 2017 20:46:17 GMT+0000 (UTC) - info: Already up-to-date.

0> Wed Dec 06 2017 20:46:17 GMT+0000 (UTC) - info: Failed to load product.json (continuing)
0> Wed Dec 06 2017 20:46:17 GMT+0000 (UTC) - info: Error: No such file
0> Wed Dec 06 2017 20:46:20 GMT+0000 (UTC) - info: finished successfully
0> Wed Dec 06 2017 20:46:20 GMT+0000 (UTC) - info: Failed to load product.json (continuing)
0> Wed Dec 06 2017 20:46:20 GMT+0000 (UTC) - info: Error: No such file
0> Wed Dec 06 2017 20:46:20 GMT+0000 (UTC) - info: loaded product.json
0> Wed Dec 06 2017 20:49:38 GMT+0000 (UTC) - info: HEAD is now at 4e63e40 removed unnecessary code

0> Wed Dec 06 2017 20:49:38 GMT+0000 (UTC) - info: Already up-to-date.

0> Wed Dec 06 2017 20:49:38 GMT+0000 (UTC) - info: Failed to load product.json (continuing)
0> Wed Dec 06 2017 20:49:38 GMT+0000 (UTC) - info: Error: No such file
0> Wed Dec 06 2017 20:50:04 GMT+0000 (UTC) - info: HEAD is now at 4e63e40 removed unnecessary code

0> Wed Dec 06 2017 20:50:05 GMT+0000 (UTC) - info: Already up-to-date.

0> Wed Dec 06 2017 20:50:06 GMT+0000 (UTC) - info: Failed to load product.json (continuing)
0> Wed Dec 06 2017 20:50:06 GMT+0000 (UTC) - info: Error: No such file
0> Wed Dec 06 2017 20:51:04 GMT+0000 (UTC) - info: HEAD is now at 4e63e40 removed unnecessary code

0> Wed Dec 06 2017 20:51:05 GMT+0000 (UTC) - info: Already up-to-date.

0> Wed Dec 06 2017 20:51:05 GMT+0000 (UTC) - info: Failed to load product.json (continuing)
0> Wed Dec 06 2017 20:51:05 GMT+0000 (UTC) - info: Error: No such file
0> Wed Dec 06 2017 20:52:04 GMT+0000 (UTC) - info: HEAD is now at 4e63e40 removed unnecessary code

0> Wed Dec 06 2017 20:52:05 GMT+0000 (UTC) - info: Already up-to-date.

0> Wed Dec 06 2017 20:52:05 GMT+0000 (UTC) - info: Failed to load product.json (continuing)
0> Wed Dec 06 2017 20:52:05 GMT+0000 (UTC) - info: Error: No such file
0> Wed Dec 06 2017 21:08:02 GMT+0000 (UTC) - info:  Error: No response from server
    at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:313:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)

```

```
0> Wed Dec 06 2017 21:08:03 GMT+0000 (UTC) - debug: task:59fb4544ae4ee000300f1699 skoudoro/brain-life-apps-dipy-segment(Brain Segmentation ) failed
0> Wed Dec 06 2017 21:08:03 GMT+0000 (UTC) - error:  Error: All configured authentication methods failed
    at tryNextAuth (/app/node_modules/ssh2/lib/client.js:380:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/app/node_modules/ssh2/lib/client.js:591:5)
    at emitTwo (events.js:106:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/app/node_modules/ssh2-streams/lib/ssh.js:3929:10)
    at SSH2Stream._transform (/app/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/app/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at SSH2Stream.Writable.write (_stream_writable.js:243:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
0> Wed Dec 06 2017 21:08:03 GMT+0000 (UTC) - debug: ssh connection ended
0> Wed Dec 06 2017 21:08:03 GMT+0000 (UTC) - debug: ssh connection closed
0> Wed Dec 06 2017 21:09:10 GMT+0000 (UTC) - error:  Error: Keepalive timeout
    at Timeout.sendKA (/app/node_modules/ssh2/lib/client.js:261:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
0> Wed Dec 06 2017 21:09:10 GMT+0000 (UTC) - debug: ssh connection closed

```

I need to fix this, but I should also consider adding suicide code to force stuck loop from resume running..

**Comment by soichih** [comment]
I've made many changes related to this in the last month or so. I am closing this for now.
